name: "Espressif IoT Development Framework (ESP-IDF)"

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: espressif/esp32-ci-env
      env:
        IDF_TARGET: esp32
      volumes:
        - /:/app/
      options: -w "/app/"
    steps:
      - name: Show files
        run: ls -ld $(find . -type f -not -path '*/\.git/*')
      - name: Cat source code
        run: cat ./main/*.c
      - name: Run ESP-IDF docker image and build command
        run: idf.py build
