name: "Espressif IoT Development Framework (ESP-IDF)"

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: espressif/esp32-ci-env
          options: -v ${{ github.workspace }}/app -w /app/
          run: |
            ls -ld $(find . -type f -not -path '*/\.git/*')
            cat ./main/*.c
            idf.py build
