name: "Espressif IoT Development Framework (ESP-IDF)"
description: "This action builds your firmware for ESP32 directly in GitHub using Espressif ESP-IDF Docker image."

on:
  push:
    branches:
      - dev

jobs:
  runs-on: ubuntu-latest
  steps:
    - run: |
        export IDF_TARGET=$(echo "esp32" | tr '[:upper:]' '[:lower:]' | tr -d '_-') 
        docker run -t -e IDF_TARGET="esp32" -v "/:/app/${{ github.repository }}" -w "/app/${{ github.repository }}/" espressif/idf:latest idf.py
      shell: bash