name: "Espressif IoT Development Framework (ESP-IDF)"

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run the build process with Docker
        run: docker run -t -e IDF_TARGET="esp32" -v ${{ github.workspace }}:/app/${{ github.repository }}/ -w /app/${{ github.repository }}/ espressif/idf:latest idf.py build
      - name: Show files
        run: |
          pwd
          ls -ld $(find . -type f -not -path '*/\.git/*' -not -path '*/build/**/*')
          cat ./main/*.c
