name: "Espressif IoT Development Framework (ESP-IDF)"

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: espressif/idf:latest
          options: -v ${{ github.workspace }}:/app/${{ github.repository }}/ -w /app/${{ github.repository }}/ idf.py build
          run: |
            pwd
            ls -ld $(find . -type f -not -path '*/\.git/*')
            cat ./main/*.c
