name: "Espressif IoT Development Framework (ESP-IDF)"

on: [push]

jobs:
  code-checkout:
    name: Checkout repository code to runner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:latest
      env:
        IDF_TARGET: esp32
      volumes:
        - /:/app/
      options: -w "/app/"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Exports IDF_TARGET env variable
        run: export IDF_TARGET=$(echo "esp32" | tr '[:upper:]' '[:lower:]' | tr -d '_-')
      - name: Show files
        run: ls -a
      - name: Show docker help
        run: docker --help
      - name: Run docker
        run: docker run
      - name: Run ESP-IDF docker image and build command
        run: idf.py build
